[package]
name = "saneput-proc"
description = "Procedural macro for saneput"
version = "0.2.0"
edition = "2021"
repository = "https://github.com/ItsEthra/saneput"
license = "MIT"
authors = ["ItsEthra"]

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
proc-macro2 = "1.0"
