[package]
name = "saneput"
description = "Sane reading of stdin"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/ItsEthra/saeput"
authors = ["ItsEthra"]

[dependencies]
saneput-proc = { path = "saneput-proc" }
