[package]
name = "saneput"
description = "Sane input reading library"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/ItsEthra/saneput"
authors = ["ItsEthra"]
readme = "README.md"

[dependencies]
saneput-proc = { path = "saneput-proc" }

[workspace]
members = ["saneput-proc"]
