[package]
name = "saneput"
description = "Sane reading of stdin"
version = "0.2.0"
edition = "2021"
repository = "https://github.com/ItsEthra/saeput"
authors = ["ItsEthra"]
readme = "README.md"

[dependencies]
saneput-proc = { path = "saneput-proc" }
