[package]
name = "saneput"
description = "Sane input reading library"
version = "0.2.0"
edition = "2021"
repository = "https://github.com/ItsEthra/saneput"
authors = ["ItsEthra"]
license = "MIT"
readme = "README.md"

[dependencies]
saneput-proc = "0.2" 

[workspace]
members = ["saneput-proc"]
